openapi: 3.0.0
info:
  title: Cocobase API
  description: API Documentation for Cocobase Project
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://be-cocobase-main.vercel.app/api/v1
    description: Production server
paths:
  /auth/login:
    post:
      summary: Login Admin
      responses:
        '200':
          description: Login successful
